### ISSUE TITLE
Error: Cannot find module 'laravel-elixir/ingredients/commands/Utilities'

### ISSUE THREAD

**Issue by semsphy** [peterreisz/laravel-elixir-ngtemplatecache#1]
After I updated laravel-elixir to 3.0, I got this error

``` javascript
module.js:340
    throw err;
          ^
Error: Cannot find module 'laravel-elixir/ingredients/commands/Utilities'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/semsphy/projects/guiddies/node_modules/laravel-elixir-ngtemplatecache/index.js:8:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by peterreisz** [comment]
Thanks for reporting the issue, fixed in version 0.2.0.

**Comment by semsphy** [comment]
Thanks for fixing the problem.
